### ISSUE TITLE
Crash on startup with 800x600 screen resolution

### ISSUE THREAD

**Issue by scribblemaniac** [KaOSx/calamares#96]
**Describe the bug**
I was trying to install KaOS from KaOS Live in VirtualBox, however the installer would always immediately crash. Based on the backtrace from the Crash Reporter and some further testing, I was able to determine cause of the issue. Calamares has a minimum width of 800px: https://github.com/KaOSx/calamares/blob/6db456d13eb7775f3ed6d10f39e65e0e15df1e57/src/libcalamaresui/utils/Gui.h#L95

The default resolution of VirtualBox is 800x600 unless changed manually or the guest additions is installed and should work with Calamares. However, because the KaOS Live defaults to having the dock/panel on the right hand side, the actual available width for windows is less than 800px. This causes a crash here:
https://github.com/KaOSx/calamares/blob/6db456d13eb7775f3ed6d10f39e65e0e15df1e57/src/calamares/CalamaresWindow.cpp#L430

`availableSize.width()` is less than `minimumSize.width()` so qBound crashes with an assertion error.

**To Reproduce**
1. Start the KaOS live image.
2. Make sure the panel is configured to be positioned to the left or right side (the default configuration) and the display resolution is set to 800x600.
3. Attempt to open the Calameres installer through the startup window or the application launcher.
4. Crash.

**Expected behavior**
The installer should work and not crash with the default VirtualBox configuration. It should work with 800x600 displays, which while not common anymore, could conceivably be used in some other situations as well. Because the upstream Calameres application theoretically does work with 800x600 displays already and it is the default configuration of KaOS Live that further restricts the screen real estate, I am reporting this as a distro issue and not an upstream app issue.

**Additional context**
<details>
<summary>Crash Handler Developer Information</summary>
Application: Calamares (calamares), signal: Aborted

[KCrash Handler]
#4  0x00007f2acbcab28c in __pthread_kill_implementation () at /lib/libc.so.6
#5  0x00007f2acbc5ea62 in raise () at /lib/libc.so.6
#6  0x00007f2acbc484df in abort () at /lib/libc.so.6
#7  0x00007f2acc2b5af6 in qAbort() () at /usr/lib/libQt6Core.so.6
#8  0x00007f2acc2ec7ad in ??? () at /usr/lib/libQt6Core.so.6
#9  0x00007f2acc2b6682 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/libQt6Core.so.6
#10 0x00007f2acc2b5a74 in qt_assert(char const*, char const*, int) () at /usr/lib/libQt6Core.so.6
#11 0x0000000000428c01 in qBound<int> (min=@0x7ffe7c082770: 800, val=@0x7ffe7c08276c: 920, max=@0x7ffe7c082768: 756) at /usr/include/qt6/QtCore/qminmax.h:46
#12 0x0000000000426d07 in CalamaresWindow::CalamaresWindow (this=this@entry=0x325b7300, parent=parent@entry=0x0) at /usr/src/debug/calamares/calamares/src/calamares/CalamaresWindow.cpp:430
#13 0x0000000000423c1b in CalamaresApplication::initView (this=0x7ffe7c082f60) at /usr/src/debug/calamares/calamares/src/calamares/CalamaresApplication.cpp:255
#14 0x00000000004253b4 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (CalamaresApplication::*)()>::call(void (CalamaresApplication::*)(), CalamaresApplication*, void**) (f=(void (CalamaresApplication::*)(CalamaresApplication * const)) 0x423b90 <CalamaresApplication::initView()>, o=0x7ffe7c082f60, arg=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:145
#15 0x00000000004253f1 in QtPrivate::FunctionPointer<void (CalamaresApplication::*)()>::call<QtPrivate::List<>, void>(void (CalamaresApplication::*)(), CalamaresApplication*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#16 QtPrivate::QCallableObject<void (CalamaresApplication::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:553
#17 0x00007f2acc3bb5c0 in ??? () at /usr/lib/libQt6Core.so.6
#18 0x00007f2acedc3f0a in Calamares::ModuleManager::initDone (this=<optimized out>) at /usr/src/debug/calamares/build/src/libcalamaresui/calamaresui_autogen/RUACCQ4MTV/moc_ModuleManager.cpp:190
#19 0x0000000000425c5c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Calamares::ModuleManager::*)()>::call(void (Calamares::ModuleManager::*)(), Calamares::ModuleManager*, void**) (f=(void (Calamares::ModuleManager::*)(Calamares::ModuleManager * const)) 0x7f2acedc3ef0 <Calamares::ModuleManager::initDone()>, o=0x325a6840, arg=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:145
#20 0x0000000000425c99 in QtPrivate::FunctionPointer<void (Calamares::ModuleManager::*)()>::call<QtPrivate::List<>, void>(void (Calamares::ModuleManager::*)(), Calamares::ModuleManager*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#21 QtPrivate::QCallableObject<void (Calamares::ModuleManager::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:553
#22 0x00007f2acc3bb5c0 in ??? () at /usr/lib/libQt6Core.so.6
#23 0x00007f2acc2dcc6a in QProcess::setupChildProcess() () at /usr/lib/libQt6Core.so.6
#24 0x00007f2acc3ada4f in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#25 0x00007f2acd77cae1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#26 0x00007f2acc35d388 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#27 0x00007f2acc4f9fda in QTimerInfoList::activateTimers() () at /usr/lib/libQt6Core.so.6
#28 0x00007f2acc60de24 in ??? () at /usr/lib/libQt6Core.so.6
#29 0x00007f2acad14234 in ??? () at /usr/lib/libglib-2.0.so.0
#30 0x00007f2acad170c7 in ??? () at /usr/lib/libglib-2.0.so.0
#31 0x00007f2acad176ac in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007f2acc60e08c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#33 0x00007f2acc368d2b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#34 0x00007f2acc365722 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#35 0x0000000000422155 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/calamares/calamares/src/calamares/main.cpp:154
[Inferior 1 (process 1939) detached]
</details>

**Comment by scribblemaniac** [comment]
VirtualBox is a something many people use to test distros. Every time you create a new machine, it defaults to a 800x600 display so it's not matter of how many people "desire" this resolution, but rather how many people would know to change this before running the installer. I don't understand how reducing the minimum width of this application by 50px is degrading the user experience more than having an OS installer crash without explanation with the default configuration of one of the most popular virtualization tools.

Suggesting that because nobody's reported the bug to you before that it's not worth fixing is also a disappointing stance to take. It was [reported and fixed 7 years ago](https://github.com/calamares/calamares/issues/731) for every other distro without a vertical dock that uses Calameres. Perhaps there simply was not anyone trying KaOS for the first time who felt invested enough in the project to go through the process of reporting the issue. Who can blame them when this is the kind of response they can expect?
